---

- name: Installing yum repository
  yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm

- name: Installing yum repository
  yum: name=epel-release

- name: Installing Required packages for Xtrabackup
  yum: name={{ item }}
  with_items:
    - socat
    - qpress
    - daemon
    - percona-xtrabackup
  retries: 2
  ignore_errors: yes
